let employees = [{ "id": 1, "name": "Alonzo", "email": "abessom0@chicagotribune.com", "gender": "Male" },
{ "id": 2, "name": "Dick", "email": "ddupree1@ed.gov", "gender": "Male" },
{ "id": 3, "name": "Blondelle", "email": "bworrill2@mapquest.com", "gender": "Female" },
{ "id": 4, "name": "Marj", "email": "mshapcote3@msn.com", "gender": "Female" },
{ "id": 5, "name": "Amity", "email": "aguild4@privacy.gov.au", "gender": "Female" },
{ "id": 6, "name": "Fraze", "email": "fchildrens5@sphinn.com", "gender": "Genderqueer" },
{ "id": 7, "name": "Darb", "email": "dherity6@odnoklassniki.ru", "gender": "Male" },
{ "id": 8, "name": "Glenna", "email": "gmcaneny7@deliciousdays.com", "gender": "Female" },
{ "id": 9, "name": "Belita", "email": "bdrage8@sciencedirect.com", "gender": "Female" },
{ "id": 10, "name": "Craggie", "email": "cainley9@privacy.gov.au", "gender": "Male" },
{ "id": 11, "name": "Ax", "email": "abradanea@pen.io", "gender": "Male" },
{ "id": 12, "name": "Baldwin", "email": "bgriseb@123-reg.co.uk", "gender": "Male" },
{ "id": 13, "name": "Christine", "email": "cderricoc@toplist.cz", "gender": "Female" },
{ "id": 14, "name": "Margarette", "email": "mpenasd@jugem.jp", "gender": "Female" },
{ "id": 15, "name": "Arty", "email": "athornhille@simplemachines.org", "gender": "Male" },
{ "id": 16, "name": "Sara-ann", "email": "sedwinf@fotki.com", "gender": "Female" },
{ "id": 17, "name": "Guglielmo", "email": "gchellamg@pcworld.com", "gender": "Male" },
{ "id": 18, "name": "Sonnie", "email": "sgidneyh@economist.com", "gender": "Female" },
{ "id": 19, "name": "Cynthia", "email": "cmilneri@japanpost.jp", "gender": "Female" },
{ "id": 20, "name": "Cherice", "email": "cwillsherej@booking.com", "gender": "Female" },
{ "id": 21, "name": "Ashly", "email": "agullimank@icq.com", "gender": "Female" },
{ "id": 22, "name": "Lisette", "email": "lnanal@blogtalkradio.com", "gender": "Female" },
{ "id": 23, "name": "Elwood", "email": "eedgettm@about.me", "gender": "Male" },
{ "id": 24, "name": "Gabriele", "email": "gjenicken@cbc.ca", "gender": "Male" },
{ "id": 25, "name": "Suzanne", "email": "shartello@odnoklassniki.ru", "gender": "Female" },
{ "id": 26, "name": "Melicent", "email": "mbelchemp@joomla.org", "gender": "Female" },
{ "id": 27, "name": "Gamaliel", "email": "gwessonq@cloudflare.com", "gender": "Male" },
{ "id": 28, "name": "Kalvin", "email": "krosler@aboutads.info", "gender": "Non-binary" },
{ "id": 29, "name": "Mata", "email": "miacominis@twitter.com", "gender": "Male" },
{ "id": 30, "name": "Charo", "email": "cviggerst@economist.com", "gender": "Female" },
{ "id": 31, "name": "Lorry", "email": "lpyneu@ftc.gov", "gender": "Female" },
{ "id": 32, "name": "Hyatt", "email": "hvolkesv@ning.com", "gender": "Male" },
{ "id": 33, "name": "Dick", "email": "dprimew@macromedia.com", "gender": "Male" },
{ "id": 34, "name": "Ravid", "email": "rhardagex@adobe.com", "gender": "Male" },
{ "id": 35, "name": "Jacques", "email": "jscurrahy@slideshare.net", "gender": "Male" },
{ "id": 36, "name": "Sean", "email": "sstannahz@blinklist.com", "gender": "Male" },
{ "id": 37, "name": "Andra", "email": "ahead10@google.fr", "gender": "Female" },
{ "id": 38, "name": "Guthrey", "email": "gsprague11@domainmarket.com", "gender": "Male" },
{ "id": 39, "name": "Tremayne", "email": "tpottes12@yolasite.com", "gender": "Male" },
{ "id": 40, "name": "Giorgia", "email": "gloseke13@e-recht24.de", "gender": "Female" },
{ "id": 41, "name": "Ambros", "email": "amanicomb14@cbslocal.com", "gender": "Male" },
{ "id": 42, "name": "Radcliffe", "email": "rferminger15@upenn.edu", "gender": "Male" },
{ "id": 43, "name": "Lockwood", "email": "lhaliday16@sohu.com", "gender": "Male" },
{ "id": 44, "name": "Rodolfo", "email": "rcolisbe17@zdnet.com", "gender": "Male" },
{ "id": 45, "name": "Pia", "email": "pmarland18@ebay.com", "gender": "Genderqueer" },
{ "id": 46, "name": "Karlene", "email": "kschaffler19@blinklist.com", "gender": "Female" },
{ "id": 47, "name": "Harlen", "email": "hgosden1a@1688.com", "gender": "Male" },
{ "id": 48, "name": "Benito", "email": "bkirk1b@home.pl", "gender": "Male" },
{ "id": 49, "name": "Chandal", "email": "cthunder1c@odnoklassniki.ru", "gender": "Female" },
{ "id": 50, "name": "Courtenay", "email": "csenn1d@list-manage.com", "gender": "Female" },
{ "id": 51, "name": "Ham", "email": "hminton1e@istockphoto.com", "gender": "Male" },
{ "id": 52, "name": "Rocky", "email": "rsilvers1f@edublogs.org", "gender": "Male" },
{ "id": 53, "name": "Prentiss", "email": "pswinburne1g@webs.com", "gender": "Male" },
{ "id": 54, "name": "Lin", "email": "lseifert1h@usnews.com", "gender": "Male" },
{ "id": 55, "name": "Heinrick", "email": "hcharle1i@mit.edu", "gender": "Male" },
{ "id": 56, "name": "Mikkel", "email": "mmaryin1j@g.co", "gender": "Male" },
{ "id": 57, "name": "Thea", "email": "tphilips1k@intel.com", "gender": "Genderfluid" },
{ "id": 58, "name": "Joellen", "email": "jmarushak1l@comsenz.com", "gender": "Female" },
{ "id": 59, "name": "Morley", "email": "mhowle1m@newyorker.com", "gender": "Male" },
{ "id": 60, "name": "Henderson", "email": "hboram1n@timesonline.co.uk", "gender": "Male" },
{ "id": 61, "name": "Aveline", "email": "astedall1o@sohu.com", "gender": "Genderfluid" },
{ "id": 62, "name": "Trent", "email": "tleet1p@nih.gov", "gender": "Male" },
{ "id": 63, "name": "Ozzy", "email": "odurrington1q@washington.edu", "gender": "Polygender" },
{ "id": 64, "name": "Lionel", "email": "lscroggins1r@addthis.com", "gender": "Male" },
{ "id": 65, "name": "Olly", "email": "obailey1s@cnn.com", "gender": "Female" },
{ "id": 66, "name": "Glennis", "email": "gjowling1t@arizona.edu", "gender": "Female" },
{ "id": 67, "name": "Alexandros", "email": "amazzei1u@topsy.com", "gender": "Male" },
{ "id": 68, "name": "Abbe", "email": "ahillyatt1v@addtoany.com", "gender": "Female" },
{ "id": 69, "name": "Yehudit", "email": "ybattson1w@gravatar.com", "gender": "Male" },
{ "id": 70, "name": "Evangelina", "email": "ecalam1x@adobe.com", "gender": "Female" },
{ "id": 71, "name": "Rubin", "email": "rheugle1y@xing.com", "gender": "Male" },
{ "id": 72, "name": "Tammie", "email": "tsaltmarsh1z@google.ru", "gender": "Male" },
{ "id": 73, "name": "Riane", "email": "rreddy20@issuu.com", "gender": "Female" },
{ "id": 74, "name": "Kai", "email": "kthrelkeld21@desdev.cn", "gender": "Female" },
{ "id": 75, "name": "Maighdiln", "email": "miiannoni22@blogtalkradio.com", "gender": "Female" },
{ "id": 76, "name": "Flinn", "email": "fkillbey23@gizmodo.com", "gender": "Male" },
{ "id": 77, "name": "Simona", "email": "sbockler24@diigo.com", "gender": "Female" },
{ "id": 78, "name": "Gena", "email": "ggallo25@reference.com", "gender": "Female" },
{ "id": 79, "name": "Jade", "email": "jsuttie26@marriott.com", "gender": "Female" },
{ "id": 80, "name": "Jory", "email": "jalessandretti27@alexa.com", "gender": "Male" },
{ "id": 81, "name": "Malachi", "email": "mbroad28@ft.com", "gender": "Male" },
{ "id": 82, "name": "Dimitri", "email": "dtarplee29@eepurl.com", "gender": "Male" },
{ "id": 83, "name": "Lek", "email": "lwoollhead2a@simplemachines.org", "gender": "Agender" },
{ "id": 84, "name": "Felicia", "email": "fackroyd2b@pcworld.com", "gender": "Female" },
{ "id": 85, "name": "Rae", "email": "rscase2c@europa.eu", "gender": "Female" },
{ "id": 86, "name": "Kata", "email": "ksowman2d@ebay.com", "gender": "Female" },
{ "id": 87, "name": "Buffy", "email": "beade2e@storify.com", "gender": "Female" },
{ "id": 88, "name": "Tresa", "email": "thearsey2f@desdev.cn", "gender": "Female" },
{ "id": 89, "name": "Mela", "email": "mtambling2g@webeden.co.uk", "gender": "Female" },
{ "id": 90, "name": "Murvyn", "email": "mshirer2h@toplist.cz", "gender": "Male" },
{ "id": 91, "name": "Buffy", "email": "bmatias2i@springer.com", "gender": "Female" },
{ "id": 92, "name": "Simmonds", "email": "skort2j@ustream.tv", "gender": "Male" },
{ "id": 93, "name": "Melisande", "email": "mblazy2k@weebly.com", "gender": "Female" },
{ "id": 94, "name": "Wilton", "email": "wwallice2l@columbia.edu", "gender": "Male" },
{ "id": 95, "name": "Darcy", "email": "dgladbach2m@gizmodo.com", "gender": "Male" },
{ "id": 96, "name": "Gwyn", "email": "gdrew2n@japanpost.jp", "gender": "Female" },
{ "id": 97, "name": "Brandtr", "email": "bbrislane2o@free.fr", "gender": "Male" },
{ "id": 98, "name": "Shirlee", "email": "slissaman2p@a8.net", "gender": "Female" },
{ "id": 99, "name": "Goldy", "email": "gpepperell2q@theguardian.com", "gender": "Female" },
{ "id": 100, "name": "Hetty", "email": "hsharpe2r@netscape.com", "gender": "Female" }]

function display_Data() {

    let rows = ""
    employees.forEach((employee) => {
        rows = rows + `<tr>  
                        <td>${employee.id}</td>
                        <td>${employee.name}</td>
                        <td>${employee.email}</td>
                        <td>${employee.gender}</td>
                        </tr>`
    })
    //document.getElementById('tbody_Data').innerHTML = "GM"
    document.getElementById('tbody_Data').innerHTML = rows
}

