let users = [{ "id": 1, "name": "Julina", "email": "jbutlin0@wikia.com" },
{ "id": 2, "name": "Dre", "email": "dorto1@chicagotribune.com" },
{ "id": 3, "name": "Rochette", "email": "rghelardoni2@vkontakte.ru" },
{ "id": 4, "name": "Wenona", "email": "wwardle3@zdnet.com" },
{ "id": 5, "name": "Nedi", "email": "nwestfalen4@ow.ly" },
{ "id": 6, "name": "Fonz", "email": "fellesmere5@jalbum.net" },
{ "id": 7, "name": "Deva", "email": "dwestover6@newyorker.com" },
{ "id": 8, "name": "Blinnie", "email": "bhourican7@about.com" },
{ "id": 9, "name": "Consolata", "email": "cmeineck8@amazonaws.com" },
{ "id": 10, "name": "Kristin", "email": "kcecil9@virginia.edu" },
{ "id": 11, "name": "Orv", "email": "opudgea@meetup.com" },
{ "id": 12, "name": "Bar", "email": "bgainsburghb@bigcartel.com" },
{ "id": 13, "name": "Alie", "email": "asighardc@foxnews.com" },
{ "id": 14, "name": "Rip", "email": "rstallardd@360.cn" },
{ "id": 15, "name": "Xymenes", "email": "xsalmonde@theglobeandmail.com" },
{ "id": 16, "name": "Lianna", "email": "ljadof@samsung.com" },
{ "id": 17, "name": "Dawna", "email": "dkittg@github.io" },
{ "id": 18, "name": "Derwin", "email": "dmckeagh@google.nl" },
{ "id": 19, "name": "Rainer", "email": "rbootelli@slashdot.org" },
{ "id": 20, "name": "Tiffanie", "email": "tshrievej@shinystat.com" },
{ "id": 21, "name": "Rodrigo", "email": "rhamshark@howstuffworks.com" },
{ "id": 22, "name": "Nelly", "email": "nsheridanl@shinystat.com" },
{ "id": 23, "name": "Cheryl", "email": "cshoebothamm@phpbb.com" },
{ "id": 24, "name": "Hailee", "email": "hscreasn@hao123.com" },
{ "id": 25, "name": "Sabine", "email": "sdoucetteo@time.com" },
{ "id": 26, "name": "Deloris", "email": "dioannidisp@google.ru" },
{ "id": 27, "name": "Maryanne", "email": "mtregaleq@comcast.net" },
{ "id": 28, "name": "Kaile", "email": "kferrierior@biblegateway.com" },
{ "id": 29, "name": "Thorsten", "email": "tsmithams@vistaprint.com" },
{ "id": 30, "name": "Alexei", "email": "adrysdellt@aol.com" },
{ "id": 31, "name": "Caryn", "email": "cpedwellu@dagondesign.com" },
{ "id": 32, "name": "Anica", "email": "akiddeyv@opera.com" },
{ "id": 33, "name": "Coralyn", "email": "cgabelw@123-reg.co.uk" },
{ "id": 34, "name": "Nil", "email": "ndurrellx@hp.com" },
{ "id": 35, "name": "Constantin", "email": "cvasiljevicy@123-reg.co.uk" },
{ "id": 36, "name": "Tillie", "email": "tkhotlerz@google.fr" },
{ "id": 37, "name": "Rudolf", "email": "rrousel10@cyberchimps.com" },
{ "id": 38, "name": "Shea", "email": "srothschild11@comcast.net" },
{ "id": 39, "name": "Clayborne", "email": "cweathey12@ocn.ne.jp" },
{ "id": 40, "name": "Garrard", "email": "grobak13@wix.com" },
{ "id": 41, "name": "Alexandre", "email": "adeveril14@bloglovin.com" },
{ "id": 42, "name": "Irv", "email": "icawdron15@constantcontact.com" },
{ "id": 43, "name": "Micah", "email": "mdighton16@chronoengine.com" },
{ "id": 44, "name": "Gwendolyn", "email": "gocarrol17@theglobeandmail.com" },
{ "id": 45, "name": "Rogers", "email": "rdurbin18@stumbleupon.com" },
{ "id": 46, "name": "Rene", "email": "rsanbrook19@oracle.com" },
{ "id": 47, "name": "Sophi", "email": "shischke1a@gmpg.org" },
{ "id": 48, "name": "Lenard", "email": "lallsobrook1b@tripod.com" },
{ "id": 49, "name": "Ginelle", "email": "ghardaker1c@desdev.cn" },
{ "id": 50, "name": "Hallie", "email": "hchang1d@4shared.com" }]

for (let i = 0; i <= users.length - 1; i++) {
    console.log(users[i].name)
}

/* for (user of users) {
    console.log(user.loc)
} */